[workspace]
authors = ["Oleksandr Petrenko <oleksandr.petrenko@mutation.me>"]
channels = ["conda-forge", "bioconda"]
name = "2025Q1-DAAD-sc-spatial"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-seurat = ">=5.2.1,<6"
r-irkernel = ">=1.3.2,<2"
r-patchwork = ">=1.3.0,<2"
r-dt = ">=0.33,<0.34"
r-shiny = ">=1.10.0,<2"
r-ggpubr = ">=0.6.0,<0.7"
r-viridis = ">=0.6.5,<0.7"
r-shinycssloaders = ">=1.1.0,<2"
r-devtools = ">=2.4.5,<3"
r-shinydashboard = ">=0.7.2,<0.8"
bioconductor-glmgampoi = ">=1.18.0,<2"
r-biocmanager = ">=1.30.25,<2"
bioconductor-genomeinfodbdata = ">=1.2.13,<2"
quarto = ">=1.6.43,<2"
